base_url = "https://rust-lang-by.github.io"
title = "Belarus Rust Community"

compile_sass = true

highlight_code = false

build_search_index = false

[extra]
greeting = "Rust BY"

iam = "We are"

links = [
    { title = "E-Mail", url = "mailto:mail@example.org", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com", icon = "github" },
    { title = "Twitter", url = "https://twitter.com", icon = "twitter" }
]

[extra.author]
name = "Belarus Rust Community"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"
